### ISSUE TITLE
部分番剧在 feedly 不能订阅

### ISSUE THREAD

**Issue by ckyOL** [wdssmq/Bilibili2RSS#3]
经过测试发现部分番剧不能在 feedly 里订阅，如 [不要输！！恶之军团！ ](http://bangumi.bilibili.com/anime/5956)、[怪怪守护神](http://bangumi.bilibili.com/anime/5988)
对此十分费解

**Comment by wdssmq** [comment]
https://bilibili2rss.bid/anime/5956
https://github.com/wdssmq/Bilibili2RSS/commit/7c35859adaf0d6fe42179e681220d50230ad9c9b
