### ISSUE TITLE
订阅音乐分区该如何处理？

### ISSUE THREAD

**Issue by Vstory** [wdssmq/Bilibili2RSS#4]
这个如何订阅音乐分区，像那些科技，动画，音乐的分区，也可以用这个订阅吗？这里的我试过了，音乐订阅不了[http://www.bilibili.com/rss.html](url)

**Comment by EMLVIRUS** [comment]
貌似本项目尚未实现？

**Comment by wdssmq** [comment]
[https://feedly.com/i/subscription/feed/http://www.bilibili.com/rss-3.xml](https://feedly.com/i/subscription/feed/http://www.bilibili.com/rss-3.xml)
官方的订阅可以用啊。。

**Comment by Vstory** [comment]
好吧，之前试了几次都是订阅不了。现在[http://www.bilibili.com/rss-3.xml](url)这个又可以了。
